name: Python package

on: [push]

jobs:
  check-generated-repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: test2333
        if: matrix.python-version == '3.8'
        run: |
          echo AAAAAAAAAAAAAA

      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check generated repo
        run: |
          make install
          ./scripts/check-generated-repo.sh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check docker commands
        if: ${{ matrix.python-version }} == '3.8'
        run: |
          ./scripts/docker-validate.sh
